version: "3.3"

services:

  node_app:
    build: ./
    container_name: grafsound-node_app
    environment:
      VIRTUAL_HOST: gsapi.bsbtoken.com
      LETSENCRYPT_HOST: gsapi.bsbtoken.com
      LETSENCRYPT_EMAIL: 'ndt.quang@tego.global'
    command: bash -c 'node main.js'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    links:
      - mysqldb
    networks:
      service_network:

  mysqldb:
    image: mysql
    restart: always
    container_name: $MYSQL_CONTAINER_NAME
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    networks:
      service_network:

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: 'nginx-proxy'
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  db-config:
  db-data:
